global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'app'
    metrics_path: /metrics
    scheme: https  # use https because Render uses TLS
    static_configs:
      - targets: ['devops-final-project-vd1u.onrender.com']
