global:
  scrape_interval: 15s
  # evaluation_interval: 15s $NS$ - what does evaluation_interval mean?

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] # $NS$ : modified from localhost -> prometheus 

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
  
  - job_name: 'app'
    static_configs:
      - targets: ['app:5000']