global:
  scrape_interval: 15s
  # evaluation_interval: 15s $NS$ - what does evaluation_interval mean?

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] # $NS$ : modified from localhost -> prometheus 

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
  
  # changed target from node exporter to host docker internal
  # Example for a backend service (replace with your actual service details)
  # - job_name: 'my-backend'
  #   static_configs:
  #     - targets: ['my-backend:8080']