name: CI PR Configuration Workflow

on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: pip install black flake8

      - name: Lint-flake8
        run: flake8 src 
      
      - name: Lint-black
        run: black src
      
  unit-job:

    runs-on: ubuntu-latest
    steps:    

      - name: checkout
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5

      - name: Install test dependencies
        run: pip install pytest

      - name: run pytest
        run: PYTHONPATH=src pytest
      

  # build-job:
  #   runs-on: ubuntu-latest
  #   needs: [lint-job, unit-job] # We require successfull lint and unit test to enable building test.
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4

  #     - name: Build-Docker-image

    